server:
  port: 8081

spring:
  application:
    name: produto-service
  datasource:
    url: jdbc:h2:mem:produtosdb
    username: valmilson
    password: valmilson
  h2:
    console:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/